stages:
  - install

# 4) Install in signup-test-container
install-in-container:
  stage: install
  script:
    - CONTAINER='signup-test-container'
    - WEBCGI='https://download.dmx.systems/cgi-bin/v1/latest-version.cgi?'
    - CIDIR='/var/www/download.dmx.systems/ci'
    - DESTDIR="${CIDIR}/${CI_PROJECT_NAME}"
    - docker exec ${CONTAINER} sh -c "rm -f /usr/share/dmx/bundle-deploy/${CI_PROJECT_NAME}-*.jar"
    - latest_version="$( /usr/bin/wget -q -O - "${WEBCGI}/ci/${CI_PROJECT_NAME}/${CI_PROJECT_NAME}-latest.jar&basename=true" )"
    - echo "Install ${latest_version} in ${CONTAINER}"
    - NUNC="$( date "+%b %d, %Y %I:%M:%S %p" )"
    - docker cp ${DESTDIR}/${latest_version} ${CONTAINER}:/usr/share/dmx/bundle-deploy/
    - sleep 10
    - LOGFILE='/var/log/dmx/dmx.log'
    - LINE="$( docker exec ${CONTAINER} sh -c "cat ${LOGFILE} | grep -B1 -n SEVERE | tail -n2 | head -n1" )"
    - echo ${NUNC}
    - echo ${LINE}
  only:
    - master
